@startuml
title Diagrama de Despliegue

node "Servidor Web\n(Java + SpringBoot)" {
    node "Aplicación" {
        component "Academia de fútbol" <<spring boot>> as SpringBoot
    }
}

database "Database" as H2

SpringBoot --> H2

@enduml
