-- 1. Creación de la tabla CATEGORIAS (necesaria para la clave ajena)
-- http://localhost:8080/h2-console
CREATE TABLE IF NOT EXISTS CATEGORIAS (
  id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL
);


-- 2. Creación de la tabla JUGADORES
CREATE TABLE IF NOT EXISTS JUGADORES (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    apellido VARCHAR(255) NOT NULL,
    edad INT NOT NULL,
    pierna_habil VARCHAR(20) NOT NULL,
    email VARCHAR(255) NOT NULL,
    categoria_id BIGINT,
    FOREIGN KEY (categoria_id) REFERENCES CATEGORIAS(id)
);



-- 3. Creamos secuencias para nuevos IDs

DROP SEQUENCE IF EXISTS CATEGORIAS_SEQ;
CREATE SEQUENCE CATEGORIAS_SEQ START WITH 100 INCREMENT BY 1;

DROP SEQUENCE IF EXISTS JUGADORES_SEQ;
CREATE SEQUENCE JUGADORES_SEQ START WITH 100 INCREMENT BY 1;




