@startuml
skinparam packageStyle rectangle
skinparam packageTitleFontSize 16
skinparam packageTitleFontColor #ffffff
skinparam packageTitleBackgroundColor #3b82f6
skinparam rectangle {
  BackgroundColor #eef2ff
  BorderColor #3b82f6
}

package "Jugadores" {
  
  package "Aplicación" {
    package "Command" {}
    package "UseCase" {}
    package "Servicio" {}
  }

  package "Dominio" {
    package "Model" {}
  }

  package "Infraestructura" {
    package "Config" {}
    package "Mapper" {}
    package "Web" {}
  }
}

package "Categoría" {
  
  package "Aplicación" {
    package "Command" {}
    package "UseCase" {}
    package "Servicio" {}
  }

  package "Dominio" {
    package "Model" {}
  }

  package "Infraestructura" {
    package "Config" {}
    package "Mapper" {}
    package "Web" {}
  }
}

@enduml
