@startuml
title Diagrama de Componentes

package "Módulo Jugadores" as Jugador{

    package "aplicacion" {
        package "service" as JugadorService
        package "useCase" as JugadorUseCase
        package "JugadorCommond" as JugadorCommond
    }

    package "dominio" {
        package "error" as JugadorError
        package "model" as JugadorModel
        package "repository" as JugadorRepository
    }

    package "infraestructura" as ij{
        package "config" as JugadorConfig
        package "db" as JugadorDb
        package "mapper" as JugadorMapper
        package "web" as JugadorWeb
    }


    JugadorUseCase ..> JugadorRepository
    JugadorRepository --> JugadorModel
    JugadorRepository --> JugadorError

    Jugador --> SpringData
    Jugador ..> Common
}

package "Módulo Common" as Common {

    package "dominio" {
        package "error" as CommonError
        package "model" as CommonModel
        package "repository" as CommonRepository
    }

    package "infraestructura" as iw{
       package "web" as CommonWeb
    }

    CommonWeb ..> CommonRepository
    CommonRepository --> CommonModel
    CommonRepository --> CommonError
}

package "Spring data" as SpringData{
    component "H2"
}
@enduml
