@startuml
title Diagrama de Componentes

package "Módulo Jugadores" as Jugador{

    package "Aplicación" {
        component "JugadorService" as JugadorService
        component "JugadorUseCase" as JugadorUseCase
        component "JugadorCommond" as JugadorCommond
    }

    package "DominioJugador" {
        component "Error" as JugadorError
        component "Model" as JugadorModel
        component "Repository" as JugadorRepository
    }

    package "infraestructura" as ij{
        component "Config" as JugadorConfig
        component "db" as JugadorDb
        component "Mapper" as JugadorMapper
        component "Web" as JugadorWeb
    }


    JugadorUseCase --> JugadorRepository
    JugadorRepository --> JugadorModel
    JugadorRepository --> JugadorError

    Jugador --> SpringData
    Jugador --> Common
}

package "Módulo Common" as Common {

    package "DominioCommon" {
        component "Error" as CommonError
        component "Model" as CommonModel
        component "Repository" as CommonRepository
    }

    package "infraestructura" as iw{
       component "Web" as CommonWeb
    }

    CommonWeb ..> CommonRepository
    CommonRepository --> CommonModel
    CommonRepository --> CommonError
}

package "Spring data" as SpringData{
    component "H2"
}

@enduml
