@startuml
title Diagrama de Despliegue

node "Servidor Web\n(Java + SpringBoot)" {
node "Aplicación" {
component "Spring Boot App" as SpringBoot
}
}

database "H2 Database" as H2

SpringBoot --> H2

@enduml